### PR TITLE
introduced the idea of a config file

### PR DESCRIPTION
**Pull request by kishy-codes**
why not have a basic shell config file for some of the properties?
i tried to implement a initial working.

### CODE REVIEW

**Comment by kishy-codes** [comment]
we can perhaps add more options in the config like download location ([#3](https://github.com/mrishu/libg-fzf/issues/3)), and mirror

**Review by mrishu — CHANGES_REQUESTED** [review]
In the commit, when the config file does not exist, the code creates it but does not source it. The default values are necessary for the code to run correctly. I think it is better for some defaults to exist in the code itself, and the user can or cannot create the config file accordingly to if they want. If the config file exists, it can be sourced to modify the defaults.

**Comment by kishy-codes** [comment]
do you think i should NOT auto-create the config file?
i think it will be better for the user to have all the editable fields in the config file initially.

if the config file is not already created, the person would just wonder what available fields are present. 
we could rather make some documentation for the config file options via the -h option.

**Review by mrishu — CHANGES_REQUESTED** [review]
I would suggest the following changes for more sh compliancy.

```
CONFIG_FILE="$HOME"/.config/libg/libg.sh

if [ -f "$CONFIG_FILE" ]; then
	source "$CONFIG_FILE"
else 
	mkdir -p "$HOME"/.config/libg > /dev/null
	printf "DEFAULT_RESPERPAGE=100 # default number of search results per page\
	\nDEFAULT_DEPTH=1 # default number of result pages to scan\
	\nLIBGEN_MIRROR=\"https://libgen.rs\" # Alternatives : *.is, *.rs, *.st" > "$CONFIG_FILE"
	source "$CONFIG_FILE"
fi
```

**Comment by kishy-codes** [comment]
would it be fine if i add a download location variable?

**Comment by mrishu** [comment]
I think that's a good idea. Just cd'ing into the download directory would be enough too.

**Comment by mrishu** [comment]
Just some minor suggestions:
1. Use `""` around variables.
2. Use single bracket `[ -f "$CONFIG_FILE" ]` for test, for sh compliancy.
3. Using `mkdir -p`, if `.config` directory doesn't exist (just in case).
4. Put `$DOWNLOAD_LOCATION` as empty by default, so that book gets downloaded into current directory by default. (at least that's how I use it)
5. `[ -z "$DOWNLOAD_LOCATION" ] || cd "$DOWNLOAD_LOCATION"` to cd only if `$DOWNLOAD_LOCATION` is non-empty.

I have done the suggested changes here:

```
CONFIG_FILE="$HOME"/.config/libg/libg.sh
if [ -f "$CONFIG_FILE" ] ; then
	source "$CONFIG_FILE"

else 
	mkdir -p "$HOME"/.config/libg > /dev/null
	printf "DEFAULT_RESPERPAGE=100 # default number of search results per page\
	\nDEFAULT_DEPTH=1 # default number of result pages to scan\
	\nLIBGEN_MIRROR=\"https://libgen.rs\" # Alternatives : *.is, *.rs, *.st\
	\nDOWNLOAD_LOCATION=\"\"" > "$CONFIG_FILE"
	source "$CONFIG_FILE"
fi

[ -z "$DOWNLOAD_LOCATION" ] || cd "$DOWNLOAD_LOCATION"
```

**Comment by kishy-codes** [comment]
i am just learning out, so i appreciate the suggestions.

**Review by mrishu — APPROVED** [review]
Merged.

**Comment by kishy-codes** [comment]
thank you for the script ;)
have been using it for a while now.

i think you can also close [#3](https://github.com/mrishu/libg-fzf/issues/3)

**Comment by mrishu** [comment]
You're welcome! :D

**Pull request merged**
